name = "fmt"
version = "0.1.0"

description = "Type-safe (string) formatting for Gleam"
licences = ["Apache-2.0", "MIT"]
repository = { type = "github", user = "mooreryan", repo = "gleam_fmt" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
